# Generated by Django 4.1.2 on 2022-11-01 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleAD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(default='', max_length=4096)),
                ('state', models.CharField(choices=[('accepted', 'Accepted'), ('review', 'Review'), ('rejected', 'Rejected')], default='review', max_length=10)),
                ('image', models.CharField(max_length=1024)),
                ('email', models.CharField(max_length=2048)),
            ],
        ),
    ]
